/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gridmancer.example.undertow.vuejs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ServerTest {
    @Test void appHasAGreeting() {
        Server classUnderTest = new Server();
        assertNotNull(classUnderTest.getGreeting(), "server should have a greeting");
        Server.main(null);
    }
}
